dist: xenial   # required for Python >= 3.7
sudo: required
language: python
services: docker
python:
  - "3.6"
  - "3.7"
  - "3.8-dev"
  
before_install:
  - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
  - source $HOME/.poetry/env
install: 
  - poetry install
script : poetry run pytest test/

# Disabled until linux client is at version 4.8.5 or newer - issues with pixelmap that are working on the windows client
#    - stage: run autotest bot
#      script:
#        # Debugging
#        - echo Current path
#        - pwd
#        - echo Project dir contents
#        - ls
#        # Build the docker image
#        - docker build -t test_image -f test/Dockerfile .
#        # Run the docker image
#        - docker run -it -d --name app test_image
#        - docker exec -i app bash -c "python test/travis_test_script.py test/autotest_bot.py"
#        # Shut down and remove container after finishing
#        - docker rm -f app
